version: '3.7'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    links:
      - backend
    volumes:
      - ./frontend/src:/usr/app/src
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always
    environment:
      - PORT=5000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=trackwizz
      - DB_PASS=password
      - DB_LIBRARY=main
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./backend/src:/usr/app/src
  db:
    image: postgres:11.6-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: trackwizz
      POSTGRES_DB: main
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - .psql/data/pgdata:/var/lib/postgresql/data/pgdata
