# DEV Dockerfile
FROM node:12.13-alpine

ARG BACKEND_NAME
ENV BACKEND_NAME=${BACKEND_NAME}

ARG FRONTEND_NAME
ENV FRONTEND_NAME=${FRONTEND_NAME}

# Create app directory
WORKDIR /usr/app

RUN yarn global add pm2

# Install app dependencies
COPY package.json .
COPY yarn.lock .

RUN yarn install

# Bundle app source
COPY tsconfig.json .
COPY src src

RUN yarn run build

EXPOSE 5000

CMD ["pm2-runtime","dist/app.js"]
